run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/run-ai/kai-bolt

issues:
  exclude-dirs:
    - bin
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: zz_generated.*\.go
      linters:
        - all

