apiVersion: optimization.nvidia.com/v1alpha1
kind: ResourceInterface
metadata:
  name: serving-knative-dev-service-v1
spec:
  structureDefinition:
    rootComponent:
      name: knativeservice
      kind:
        group: serving.knative.dev
        version: v1
        kind: Service
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
        statusMappings:
          running:
          - byConditions:
              - type: Ready
                status: "True"
    childComponents:
      - name: revision
        kind:
          group: serving.knative.dev
          version: v1
          kind: Revision
        ownerRef: knativeservice
        specDefinition:
          podTemplateSpecPath: .spec.template
        scaleDefinition:
          minReplicasPath: .spec.template.metadata.annotations["autoscaling.knative.dev/min-scale"] // 1
          maxReplicasPath: .spec.template.metadata.annotations["autoscaling.knative.dev/max-scale"]
    additionalChildKinds:
      - group: apps
        version: v1
        kind: Deployment
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: revision
          members:
            - componentName: revision
              groupByKeyPaths:
                - .metadata.labels["serving.knative.dev/revision"]
