# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: leaderworkerset-multi-template
spec:
  replicas: 3
  leaderWorkerTemplate:
    leaderTemplate:
      spec:
        containers:
          - name: nginx2
            image: nginxinc/nginx-unprivileged:1.27
            resources:
              requests:
                cpu: "500m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "1Gi"
            ports:
              - containerPort: 8080
    size: 4
    workerTemplate:
      spec:
        containers:
          - name: nginx
            image: nginxinc/nginx-unprivileged:1.27
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
            ports:
              - containerPort: 8080
status:
  conditions:
    - type: Available
      status: "False"
    - type: Progressing
      status: "True"
  readyReplicas: 2
  replicas: 3
  updatedReplicas: 3
