// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 NVIDIA Corporation

package conformance

import "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

// volatileKeys are field names whose values change between two recordings of the
// same real state (cluster identity, bookkeeping, timestamps). Removing them lets a
// re-record of an unchanged workload produce a byte-identical snapshot, so a golden
// diff reflects a real change and not noise. The metadata set matches
// controller-runtime's canonical IgnoreAutogeneratedMetadata
// (pkg/envtest/komega/equalobject.go); the timestamps and controller-uid labels
// cover the values operators write per run.
var volatileKeys = map[string]bool{
	// controller-runtime IgnoreAutogeneratedMetadata
	"resourceVersion":            true,
	"uid":                        true,
	"generation":                 true,
	"creationTimestamp":          true,
	"managedFields":              true,
	"selfLink":                   true,
	"generateName":               true,
	"deletionTimestamp":          true,
	"deletionGracePeriodSeconds": true,
	// status bookkeeping + timestamps operators stamp per run
	"observedGeneration": true,
	"lastTransitionTime": true,
	// condition messages carry live rollout text ("0 out of 1 new replicas...") that
	// churns while a workload progresses; Karta reads a condition's type/status/reason,
	// never its message, so dropping it keeps the reading and stabilises init snapshots
	"message":        true,
	"lastUpdateTime": true,
	"lastProbeTime":  true,
	"startTime":      true,
	"completionTime": true,
	// per-run random ids Jobs stamp into labels, selectors, and status bookkeeping
	"controller-uid":                     true,
	"batch.kubernetes.io/controller-uid": true,
	"uncountedTerminatedPods":            true, // status: pod UIDs pending count, transient
	"lastSuccessfulTime":                 true, // CronJob status timestamp, not read by Karta
	// runtime pod identity and state-transition timestamps operators write into
	// status (for example RayCluster status.head and status.stateTransitionTimes);
	// Karta reads state, conditions, and specs, never these, and they vary per run
	"podIP":                true,
	"podName":              true,
	"serviceIP":            true,
	"stateTransitionTimes": true,
	// per-run runtime identity in a Pod's status.containerStatuses and in operator
	// status endpoints (a NIMService clusterEndpoint carries a per-run ClusterIP)
	"containerID":     true,
	"startedAt":       true,
	"finishedAt":      true,
	"clusterEndpoint": true,
	// per-run pod and node IPs in a Pod's status; Karta reads phase, not addresses,
	// and these vary run to run (and by which node the pod landed on)
	"hostIP":  true,
	"hostIPs": true,
	"podIPs":  true,
	// per-run RayJob/RayCluster status identity: the Ray job id, the generated
	// RayCluster name and head service name (random suffixes), the dashboard URL, and
	// rayJobInfo.endTime (a timestamp); Karta reads jobStatus/state, not these
	"jobId":          true,
	"rayClusterName": true,
	"serviceName":    true,
	"dashboardURL":   true,
	"endTime":        true,
	// Kubeflow job status.replicaStatuses holds per-role active/succeeded/failed counts
	// that churn while a pod terminates; Karta reads the job's conditions, not these.
	// (Stripped as a whole subtree because the bare "active" key is read by batch Jobs.)
	"replicaStatuses": true,
}

// normalizeKeys are fields whose PRESENCE the library reads but whose value is a
// per-run timestamp, so they cannot be deleted (that would change the reading) yet
// vary between recordings. Their value is replaced with a fixed placeholder so the
// field stays present and the snapshot is byte-stable. For example a CronJob's
// status.lastScheduleTime: Karta reads running when it is non-null, initializing when
// it is null, but never reads the actual time.
var normalizeKeys = map[string]string{
	"lastScheduleTime": "2026-01-01T00:00:00Z",
}

// Sanitize removes volatile fields from a CR in place. It is a denylist: any field
// not listed is always kept, so a value the library reads is never silently
// dropped. The recorder additionally proves reading(raw) == reading(sanitized)
// before persisting, which makes the denylist safe rather than merely convenient.
func Sanitize(u *unstructured.Unstructured) {
	scrub(u.Object)
	// The kubectl last-applied annotation is large, volatile, and never read by
	// Karta; drop it explicitly since it is keyed by a full path, not a bare name.
	unstructured.RemoveNestedField(u.Object, "metadata", "annotations",
		"kubectl.kubernetes.io/last-applied-configuration")
}

func scrub(v interface{}) {
	switch x := v.(type) {
	case map[string]interface{}:
		for k := range volatileKeys {
			delete(x, k)
		}
		for k, placeholder := range normalizeKeys {
			if _, ok := x[k]; ok {
				x[k] = placeholder
			}
		}
		for _, val := range x {
			scrub(val)
		}
	case []interface{}:
		for _, val := range x {
			scrub(val)
		}
	}
}
