// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 NVIDIA Corporation

package conformance

import "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

// volatileKeys are field names whose values change between two recordings of the same real
// state (cluster identity, bookkeeping, timestamps). Karta never reads any of them, so
// stripping them makes a re-record byte-stable and a golden diff mean a real change. The
// metadata set matches controller-runtime's IgnoreAutogeneratedMetadata.
var volatileKeys = map[string]bool{
	// controller-runtime IgnoreAutogeneratedMetadata
	"resourceVersion":            true,
	"uid":                        true,
	"generation":                 true,
	"creationTimestamp":          true,
	"managedFields":              true,
	"selfLink":                   true,
	"generateName":               true,
	"deletionTimestamp":          true,
	"deletionGracePeriodSeconds": true,
	// status bookkeeping + per-run timestamps
	"observedGeneration": true,
	"lastTransitionTime": true,
	// a condition's message is live rollout text; Karta reads type/status/reason, not it
	"message":        true,
	"lastUpdateTime": true,
	"lastProbeTime":  true,
	"startTime":      true,
	"completionTime": true,
	// per-run random ids Jobs stamp into labels, selectors, and status
	"controller-uid":                     true,
	"batch.kubernetes.io/controller-uid": true,
	"uncountedTerminatedPods":            true,
	"lastSuccessfulTime":                 true,
	// per-run pod/service identity and state-transition timestamps in status
	"podIP":                true,
	"podName":              true,
	"serviceIP":            true,
	"stateTransitionTimes": true,
	"containerID":          true,
	"imageID":              true, // resolved image digest, registry-prefixed, so it varies by pull source
	"startedAt":            true,
	"finishedAt":           true,
	"clusterEndpoint":      true,
	"hostIP":               true,
	"hostIPs":              true,
	"podIPs":               true,
	// which node a pod landed on (surfaces in the extracted pod template)
	"nodeName": true,
	// kubectl last-applied annotation: large, never read; a bare key so it drops anywhere
	"kubectl.kubernetes.io/last-applied-configuration": true,
	// per-run RayJob/RayCluster identity (job id, generated names, dashboard URL, endTime)
	"jobId":          true,
	"rayClusterName": true,
	"serviceName":    true,
	"dashboardURL":   true,
	"endTime":        true,
	// Kubeflow replicaStatuses: per-role counts that churn (whole subtree; bare "active" is read by Jobs)
	"replicaStatuses": true,
}

// normalizeKeys are fields the library reads by PRESENCE but whose value is a per-run
// timestamp, so they are replaced with a placeholder instead of deleted. Example: a
// CronJob's lastScheduleTime - Karta reads null vs non-null, never the time.
var normalizeKeys = map[string]string{
	"lastScheduleTime": "2026-01-01T00:00:00Z",
}

// Sanitize strips volatile fields from a CR in place. It is a denylist, so a value the
// library reads is never dropped, and Replay strips extractions the same way - which is
// what makes the recorder's reading(raw) == reading(sanitized) proof hold.
func Sanitize(u *unstructured.Unstructured) {
	stripVolatile(u.Object)
}

func stripVolatile(v interface{}) {
	switch x := v.(type) {
	case map[string]interface{}:
		for k, val := range x {
			if volatileKeys[k] {
				delete(x, k)
				continue
			}
			if placeholder, ok := normalizeKeys[k]; ok {
				x[k] = placeholder
				continue
			}
			stripVolatile(val)
		}
	case []interface{}:
		for _, val := range x {
			stripVolatile(val)
		}
	}
}
