# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
{{- if and .Values.operator.enabled .Values.webhook.enabled (eq .Values.webhook.cert.provisionMode "auto") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karta.webhook.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karta.labels" . | nindent 4 }}
{{- end -}}
