// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 NVIDIA Corporation

// Code generated by MockGen. DO NOT EDIT.
// Source: component_factory.go
//
// Generated by this command:
//
//	mockgen -source=component_factory.go -destination=accessor_mock.go -package=resource ComponentAccessor
//

// Package resource is a generated GoMock package.
package resource

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/run-ai/kai-bolt/pkg/api/optimization/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockComponentReader is a mock of ComponentReader interface.
type MockComponentReader struct {
	ctrl     *gomock.Controller
	recorder *MockComponentReaderMockRecorder
	isgomock struct{}
}

// MockComponentReaderMockRecorder is the mock recorder for MockComponentReader.
type MockComponentReaderMockRecorder struct {
	mock *MockComponentReader
}

// NewMockComponentReader creates a new mock instance.
func NewMockComponentReader(ctrl *gomock.Controller) *MockComponentReader {
	mock := &MockComponentReader{ctrl: ctrl}
	mock.recorder = &MockComponentReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentReader) EXPECT() *MockComponentReaderMockRecorder {
	return m.recorder
}

// ExtractFragmentedPodSpec mocks base method.
func (m *MockComponentReader) ExtractFragmentedPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]FragmentedPodSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFragmentedPodSpec", ctx, definition)
	ret0, _ := ret[0].([]FragmentedPodSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFragmentedPodSpec indicates an expected call of ExtractFragmentedPodSpec.
func (mr *MockComponentReaderMockRecorder) ExtractFragmentedPodSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFragmentedPodSpec", reflect.TypeOf((*MockComponentReader)(nil).ExtractFragmentedPodSpec), ctx, definition)
}

// ExtractInstanceIds mocks base method.
func (m *MockComponentReader) ExtractInstanceIds(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractInstanceIds", ctx, definition)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractInstanceIds indicates an expected call of ExtractInstanceIds.
func (mr *MockComponentReaderMockRecorder) ExtractInstanceIds(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractInstanceIds", reflect.TypeOf((*MockComponentReader)(nil).ExtractInstanceIds), ctx, definition)
}

// ExtractPodMetadata mocks base method.
func (m *MockComponentReader) ExtractPodMetadata(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v10.ObjectMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodMetadata", ctx, definition)
	ret0, _ := ret[0].([]v10.ObjectMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodMetadata indicates an expected call of ExtractPodMetadata.
func (mr *MockComponentReaderMockRecorder) ExtractPodMetadata(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodMetadata", reflect.TypeOf((*MockComponentReader)(nil).ExtractPodMetadata), ctx, definition)
}

// ExtractPodSpec mocks base method.
func (m *MockComponentReader) ExtractPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v1.PodSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodSpec", ctx, definition)
	ret0, _ := ret[0].([]v1.PodSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodSpec indicates an expected call of ExtractPodSpec.
func (mr *MockComponentReaderMockRecorder) ExtractPodSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodSpec", reflect.TypeOf((*MockComponentReader)(nil).ExtractPodSpec), ctx, definition)
}

// ExtractPodTemplateSpec mocks base method.
func (m *MockComponentReader) ExtractPodTemplateSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v1.PodTemplateSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodTemplateSpec", ctx, definition)
	ret0, _ := ret[0].([]v1.PodTemplateSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodTemplateSpec indicates an expected call of ExtractPodTemplateSpec.
func (mr *MockComponentReaderMockRecorder) ExtractPodTemplateSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodTemplateSpec", reflect.TypeOf((*MockComponentReader)(nil).ExtractPodTemplateSpec), ctx, definition)
}

// ExtractScale mocks base method.
func (m *MockComponentReader) ExtractScale(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]Scale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractScale", ctx, definition)
	ret0, _ := ret[0].([]Scale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractScale indicates an expected call of ExtractScale.
func (mr *MockComponentReaderMockRecorder) ExtractScale(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractScale", reflect.TypeOf((*MockComponentReader)(nil).ExtractScale), ctx, definition)
}

// ExtractStatus mocks base method.
func (m *MockComponentReader) ExtractStatus(ctx context.Context, definition v1alpha1.ComponentDefinition) (*Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractStatus", ctx, definition)
	ret0, _ := ret[0].(*Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractStatus indicates an expected call of ExtractStatus.
func (mr *MockComponentReaderMockRecorder) ExtractStatus(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractStatus", reflect.TypeOf((*MockComponentReader)(nil).ExtractStatus), ctx, definition)
}

// GetObject mocks base method.
func (m *MockComponentReader) GetObject() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockComponentReaderMockRecorder) GetObject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockComponentReader)(nil).GetObject))
}

// MockComponentWriter is a mock of ComponentWriter interface.
type MockComponentWriter struct {
	ctrl     *gomock.Controller
	recorder *MockComponentWriterMockRecorder
	isgomock struct{}
}

// MockComponentWriterMockRecorder is the mock recorder for MockComponentWriter.
type MockComponentWriterMockRecorder struct {
	mock *MockComponentWriter
}

// NewMockComponentWriter creates a new mock instance.
func NewMockComponentWriter(ctrl *gomock.Controller) *MockComponentWriter {
	mock := &MockComponentWriter{ctrl: ctrl}
	mock.recorder = &MockComponentWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentWriter) EXPECT() *MockComponentWriterMockRecorder {
	return m.recorder
}

// UpdateFragmentedPodSpec mocks base method.
func (m *MockComponentWriter) UpdateFragmentedPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition, fragmentedPodSpecs []FragmentedPodSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFragmentedPodSpec", ctx, definition, fragmentedPodSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFragmentedPodSpec indicates an expected call of UpdateFragmentedPodSpec.
func (mr *MockComponentWriterMockRecorder) UpdateFragmentedPodSpec(ctx, definition, fragmentedPodSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFragmentedPodSpec", reflect.TypeOf((*MockComponentWriter)(nil).UpdateFragmentedPodSpec), ctx, definition, fragmentedPodSpecs)
}

// UpdatePodMetadata mocks base method.
func (m *MockComponentWriter) UpdatePodMetadata(ctx context.Context, definition v1alpha1.ComponentDefinition, podMetadata []v10.ObjectMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePodMetadata", ctx, definition, podMetadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePodMetadata indicates an expected call of UpdatePodMetadata.
func (mr *MockComponentWriterMockRecorder) UpdatePodMetadata(ctx, definition, podMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePodMetadata", reflect.TypeOf((*MockComponentWriter)(nil).UpdatePodMetadata), ctx, definition, podMetadata)
}

// UpdatePodSpec mocks base method.
func (m *MockComponentWriter) UpdatePodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition, podSpecs []v1.PodSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePodSpec", ctx, definition, podSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePodSpec indicates an expected call of UpdatePodSpec.
func (mr *MockComponentWriterMockRecorder) UpdatePodSpec(ctx, definition, podSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePodSpec", reflect.TypeOf((*MockComponentWriter)(nil).UpdatePodSpec), ctx, definition, podSpecs)
}

// UpdatePodTemplateSpec mocks base method.
func (m *MockComponentWriter) UpdatePodTemplateSpec(ctx context.Context, definition v1alpha1.ComponentDefinition, podTemplateSpecs []v1.PodTemplateSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePodTemplateSpec", ctx, definition, podTemplateSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePodTemplateSpec indicates an expected call of UpdatePodTemplateSpec.
func (mr *MockComponentWriterMockRecorder) UpdatePodTemplateSpec(ctx, definition, podTemplateSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePodTemplateSpec", reflect.TypeOf((*MockComponentWriter)(nil).UpdatePodTemplateSpec), ctx, definition, podTemplateSpecs)
}

// MockComponentAccessor is a mock of ComponentAccessor interface.
type MockComponentAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockComponentAccessorMockRecorder
	isgomock struct{}
}

// MockComponentAccessorMockRecorder is the mock recorder for MockComponentAccessor.
type MockComponentAccessorMockRecorder struct {
	mock *MockComponentAccessor
}

// NewMockComponentAccessor creates a new mock instance.
func NewMockComponentAccessor(ctrl *gomock.Controller) *MockComponentAccessor {
	mock := &MockComponentAccessor{ctrl: ctrl}
	mock.recorder = &MockComponentAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComponentAccessor) EXPECT() *MockComponentAccessorMockRecorder {
	return m.recorder
}

// ExtractFragmentedPodSpec mocks base method.
func (m *MockComponentAccessor) ExtractFragmentedPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]FragmentedPodSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFragmentedPodSpec", ctx, definition)
	ret0, _ := ret[0].([]FragmentedPodSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFragmentedPodSpec indicates an expected call of ExtractFragmentedPodSpec.
func (mr *MockComponentAccessorMockRecorder) ExtractFragmentedPodSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFragmentedPodSpec", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractFragmentedPodSpec), ctx, definition)
}

// ExtractInstanceIds mocks base method.
func (m *MockComponentAccessor) ExtractInstanceIds(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractInstanceIds", ctx, definition)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractInstanceIds indicates an expected call of ExtractInstanceIds.
func (mr *MockComponentAccessorMockRecorder) ExtractInstanceIds(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractInstanceIds", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractInstanceIds), ctx, definition)
}

// ExtractPodMetadata mocks base method.
func (m *MockComponentAccessor) ExtractPodMetadata(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v10.ObjectMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodMetadata", ctx, definition)
	ret0, _ := ret[0].([]v10.ObjectMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodMetadata indicates an expected call of ExtractPodMetadata.
func (mr *MockComponentAccessorMockRecorder) ExtractPodMetadata(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodMetadata", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractPodMetadata), ctx, definition)
}

// ExtractPodSpec mocks base method.
func (m *MockComponentAccessor) ExtractPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v1.PodSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodSpec", ctx, definition)
	ret0, _ := ret[0].([]v1.PodSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodSpec indicates an expected call of ExtractPodSpec.
func (mr *MockComponentAccessorMockRecorder) ExtractPodSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodSpec", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractPodSpec), ctx, definition)
}

// ExtractPodTemplateSpec mocks base method.
func (m *MockComponentAccessor) ExtractPodTemplateSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v1.PodTemplateSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodTemplateSpec", ctx, definition)
	ret0, _ := ret[0].([]v1.PodTemplateSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodTemplateSpec indicates an expected call of ExtractPodTemplateSpec.
func (mr *MockComponentAccessorMockRecorder) ExtractPodTemplateSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodTemplateSpec", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractPodTemplateSpec), ctx, definition)
}

// ExtractScale mocks base method.
func (m *MockComponentAccessor) ExtractScale(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]Scale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractScale", ctx, definition)
	ret0, _ := ret[0].([]Scale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractScale indicates an expected call of ExtractScale.
func (mr *MockComponentAccessorMockRecorder) ExtractScale(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractScale", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractScale), ctx, definition)
}

// ExtractStatus mocks base method.
func (m *MockComponentAccessor) ExtractStatus(ctx context.Context, definition v1alpha1.ComponentDefinition) (*Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractStatus", ctx, definition)
	ret0, _ := ret[0].(*Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractStatus indicates an expected call of ExtractStatus.
func (mr *MockComponentAccessorMockRecorder) ExtractStatus(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractStatus", reflect.TypeOf((*MockComponentAccessor)(nil).ExtractStatus), ctx, definition)
}

// GetObject mocks base method.
func (m *MockComponentAccessor) GetObject() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockComponentAccessorMockRecorder) GetObject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockComponentAccessor)(nil).GetObject))
}

// UpdateFragmentedPodSpec mocks base method.
func (m *MockComponentAccessor) UpdateFragmentedPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition, fragmentedPodSpecs []FragmentedPodSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFragmentedPodSpec", ctx, definition, fragmentedPodSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFragmentedPodSpec indicates an expected call of UpdateFragmentedPodSpec.
func (mr *MockComponentAccessorMockRecorder) UpdateFragmentedPodSpec(ctx, definition, fragmentedPodSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFragmentedPodSpec", reflect.TypeOf((*MockComponentAccessor)(nil).UpdateFragmentedPodSpec), ctx, definition, fragmentedPodSpecs)
}

// UpdatePodMetadata mocks base method.
func (m *MockComponentAccessor) UpdatePodMetadata(ctx context.Context, definition v1alpha1.ComponentDefinition, podMetadata []v10.ObjectMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePodMetadata", ctx, definition, podMetadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePodMetadata indicates an expected call of UpdatePodMetadata.
func (mr *MockComponentAccessorMockRecorder) UpdatePodMetadata(ctx, definition, podMetadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePodMetadata", reflect.TypeOf((*MockComponentAccessor)(nil).UpdatePodMetadata), ctx, definition, podMetadata)
}

// UpdatePodSpec mocks base method.
func (m *MockComponentAccessor) UpdatePodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition, podSpecs []v1.PodSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePodSpec", ctx, definition, podSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePodSpec indicates an expected call of UpdatePodSpec.
func (mr *MockComponentAccessorMockRecorder) UpdatePodSpec(ctx, definition, podSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePodSpec", reflect.TypeOf((*MockComponentAccessor)(nil).UpdatePodSpec), ctx, definition, podSpecs)
}

// UpdatePodTemplateSpec mocks base method.
func (m *MockComponentAccessor) UpdatePodTemplateSpec(ctx context.Context, definition v1alpha1.ComponentDefinition, podTemplateSpecs []v1.PodTemplateSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePodTemplateSpec", ctx, definition, podTemplateSpecs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePodTemplateSpec indicates an expected call of UpdatePodTemplateSpec.
func (mr *MockComponentAccessorMockRecorder) UpdatePodTemplateSpec(ctx, definition, podTemplateSpecs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePodTemplateSpec", reflect.TypeOf((*MockComponentAccessor)(nil).UpdatePodTemplateSpec), ctx, definition, podTemplateSpecs)
}
