// Code generated by MockGen. DO NOT EDIT.
// Source: component_factory.go
//
// Generated by this command:
//
//	mockgen -source=component_factory.go -destination=extractor_mock.go -package=resource Extractor
//

// Package resource is a generated GoMock package.
package resource

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/run-ai/kai-bolt/pkg/api/optimization/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockExtractor is a mock of Extractor interface.
type MockExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorMockRecorder
	isgomock struct{}
}

// MockExtractorMockRecorder is the mock recorder for MockExtractor.
type MockExtractorMockRecorder struct {
	mock *MockExtractor
}

// NewMockExtractor creates a new mock instance.
func NewMockExtractor(ctrl *gomock.Controller) *MockExtractor {
	mock := &MockExtractor{ctrl: ctrl}
	mock.recorder = &MockExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractor) EXPECT() *MockExtractorMockRecorder {
	return m.recorder
}

// ExtractFragmentedPodSpec mocks base method.
func (m *MockExtractor) ExtractFragmentedPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]FragmentedPodSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractFragmentedPodSpec", ctx, definition)
	ret0, _ := ret[0].([]FragmentedPodSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractFragmentedPodSpec indicates an expected call of ExtractFragmentedPodSpec.
func (mr *MockExtractorMockRecorder) ExtractFragmentedPodSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractFragmentedPodSpec", reflect.TypeOf((*MockExtractor)(nil).ExtractFragmentedPodSpec), ctx, definition)
}

// ExtractInstanceIds mocks base method.
func (m *MockExtractor) ExtractInstanceIds(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractInstanceIds", ctx, definition)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractInstanceIds indicates an expected call of ExtractInstanceIds.
func (mr *MockExtractorMockRecorder) ExtractInstanceIds(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractInstanceIds", reflect.TypeOf((*MockExtractor)(nil).ExtractInstanceIds), ctx, definition)
}

// ExtractPodMetadata mocks base method.
func (m *MockExtractor) ExtractPodMetadata(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v10.ObjectMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodMetadata", ctx, definition)
	ret0, _ := ret[0].([]v10.ObjectMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodMetadata indicates an expected call of ExtractPodMetadata.
func (mr *MockExtractorMockRecorder) ExtractPodMetadata(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodMetadata", reflect.TypeOf((*MockExtractor)(nil).ExtractPodMetadata), ctx, definition)
}

// ExtractPodSpec mocks base method.
func (m *MockExtractor) ExtractPodSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v1.PodSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodSpec", ctx, definition)
	ret0, _ := ret[0].([]v1.PodSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodSpec indicates an expected call of ExtractPodSpec.
func (mr *MockExtractorMockRecorder) ExtractPodSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodSpec", reflect.TypeOf((*MockExtractor)(nil).ExtractPodSpec), ctx, definition)
}

// ExtractPodTemplateSpec mocks base method.
func (m *MockExtractor) ExtractPodTemplateSpec(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]v1.PodTemplateSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractPodTemplateSpec", ctx, definition)
	ret0, _ := ret[0].([]v1.PodTemplateSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractPodTemplateSpec indicates an expected call of ExtractPodTemplateSpec.
func (mr *MockExtractorMockRecorder) ExtractPodTemplateSpec(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractPodTemplateSpec", reflect.TypeOf((*MockExtractor)(nil).ExtractPodTemplateSpec), ctx, definition)
}

// ExtractScale mocks base method.
func (m *MockExtractor) ExtractScale(ctx context.Context, definition v1alpha1.ComponentDefinition) ([]Scale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractScale", ctx, definition)
	ret0, _ := ret[0].([]Scale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractScale indicates an expected call of ExtractScale.
func (mr *MockExtractorMockRecorder) ExtractScale(ctx, definition any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractScale", reflect.TypeOf((*MockExtractor)(nil).ExtractScale), ctx, definition)
}
