{{- if and .Values.operator.enabled .Values.webhook.enabled (eq .Values.webhook.cert.source "certManager") -}}
{{- if not .Values.webhook.cert.certManager.issuerRef }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "karta.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karta.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "karta.webhook.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karta.labels" . | nindent 4 }}
spec:
  secretName: {{ include "karta.webhook.secretName" . }}
  dnsNames:
    - {{ include "karta.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "karta.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.webhook.cert.certManager.issuerRef }}
    {{- toYaml .Values.webhook.cert.certManager.issuerRef | nindent 4 }}
    {{- else }}
    kind: Issuer
    name: {{ include "karta.fullname" . }}-selfsigned-issuer
    {{- end }}
{{- end -}}
