{{- if and .Values.exporter.enabled .Values.exporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "karta.exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karta.exporter.labels" . | nindent 4 }}
{{- end }}
