//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentDefinition) DeepCopyInto(out *ComponentDefinition) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(GroupVersionKind)
		**out = **in
	}
	if in.OwnerRef != nil {
		in, out := &in.OwnerRef, &out.OwnerRef
		*out = new(string)
		**out = **in
	}
	if in.SpecDefinition != nil {
		in, out := &in.SpecDefinition, &out.SpecDefinition
		*out = new(SpecDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDefinition != nil {
		in, out := &in.ScaleDefinition, &out.ScaleDefinition
		*out = new(ScaleDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusDefinition != nil {
		in, out := &in.StatusDefinition, &out.StatusDefinition
		*out = new(StatusDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceIdPath != nil {
		in, out := &in.InstanceIdPath, &out.InstanceIdPath
		*out = new(string)
		**out = **in
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(PodSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentDefinition.
func (in *ComponentDefinition) DeepCopy() *ComponentDefinition {
	if in == nil {
		return nil
	}
	out := new(ComponentDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentInstanceSelector) DeepCopyInto(out *ComponentInstanceSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentInstanceSelector.
func (in *ComponentInstanceSelector) DeepCopy() *ComponentInstanceSelector {
	if in == nil {
		return nil
	}
	out := new(ComponentInstanceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentTypeSelector) DeepCopyInto(out *ComponentTypeSelector) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentTypeSelector.
func (in *ComponentTypeSelector) DeepCopy() *ComponentTypeSelector {
	if in == nil {
		return nil
	}
	out := new(ComponentTypeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsDefinition) DeepCopyInto(out *ConditionsDefinition) {
	*out = *in
	if in.MessageFieldName != nil {
		in, out := &in.MessageFieldName, &out.MessageFieldName
		*out = new(string)
		**out = **in
	}
	if in.ReasonFieldName != nil {
		in, out := &in.ReasonFieldName, &out.ReasonFieldName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsDefinition.
func (in *ConditionsDefinition) DeepCopy() *ConditionsDefinition {
	if in == nil {
		return nil
	}
	out := new(ConditionsDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedCondition) DeepCopyInto(out *ExpectedCondition) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedCondition.
func (in *ExpectedCondition) DeepCopy() *ExpectedCondition {
	if in == nil {
		return nil
	}
	out := new(ExpectedCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FragmentedPodSpecDefinition) DeepCopyInto(out *FragmentedPodSpecDefinition) {
	*out = *in
	if in.SchedulerNamePath != nil {
		in, out := &in.SchedulerNamePath, &out.SchedulerNamePath
		*out = new(string)
		**out = **in
	}
	if in.LabelsPath != nil {
		in, out := &in.LabelsPath, &out.LabelsPath
		*out = new(string)
		**out = **in
	}
	if in.AnnotationsPath != nil {
		in, out := &in.AnnotationsPath, &out.AnnotationsPath
		*out = new(string)
		**out = **in
	}
	if in.ResourcesPath != nil {
		in, out := &in.ResourcesPath, &out.ResourcesPath
		*out = new(string)
		**out = **in
	}
	if in.ResourceClaimsPath != nil {
		in, out := &in.ResourceClaimsPath, &out.ResourceClaimsPath
		*out = new(string)
		**out = **in
	}
	if in.PodAffinityPath != nil {
		in, out := &in.PodAffinityPath, &out.PodAffinityPath
		*out = new(string)
		**out = **in
	}
	if in.NodeAffinityPath != nil {
		in, out := &in.NodeAffinityPath, &out.NodeAffinityPath
		*out = new(string)
		**out = **in
	}
	if in.ContainersPath != nil {
		in, out := &in.ContainersPath, &out.ContainersPath
		*out = new(string)
		**out = **in
	}
	if in.ContainerPath != nil {
		in, out := &in.ContainerPath, &out.ContainerPath
		*out = new(string)
		**out = **in
	}
	if in.PriorityClassNamePath != nil {
		in, out := &in.PriorityClassNamePath, &out.PriorityClassNamePath
		*out = new(string)
		**out = **in
	}
	if in.ImagePath != nil {
		in, out := &in.ImagePath, &out.ImagePath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FragmentedPodSpecDefinition.
func (in *FragmentedPodSpecDefinition) DeepCopy() *FragmentedPodSpecDefinition {
	if in == nil {
		return nil
	}
	out := new(FragmentedPodSpecDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GangSchedulingInstruction) DeepCopyInto(out *GangSchedulingInstruction) {
	*out = *in
	if in.PodGroups != nil {
		in, out := &in.PodGroups, &out.PodGroups
		*out = make([]PodGroupDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GangSchedulingInstruction.
func (in *GangSchedulingInstruction) DeepCopy() *GangSchedulingInstruction {
	if in == nil {
		return nil
	}
	out := new(GangSchedulingInstruction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionKind) DeepCopyInto(out *GroupVersionKind) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionKind.
func (in *GroupVersionKind) DeepCopy() *GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationInstructions) DeepCopyInto(out *OptimizationInstructions) {
	*out = *in
	if in.GangScheduling != nil {
		in, out := &in.GangScheduling, &out.GangScheduling
		*out = new(GangSchedulingInstruction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationInstructions.
func (in *OptimizationInstructions) DeepCopy() *OptimizationInstructions {
	if in == nil {
		return nil
	}
	out := new(OptimizationInstructions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseDefinition) DeepCopyInto(out *PhaseDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseDefinition.
func (in *PhaseDefinition) DeepCopy() *PhaseDefinition {
	if in == nil {
		return nil
	}
	out := new(PhaseDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupDefinition) DeepCopyInto(out *PodGroupDefinition) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]PodGroupMemberDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupDefinition.
func (in *PodGroupDefinition) DeepCopy() *PodGroupDefinition {
	if in == nil {
		return nil
	}
	out := new(PodGroupDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupMemberDefinition) DeepCopyInto(out *PodGroupMemberDefinition) {
	*out = *in
	if in.GroupByKeyPaths != nil {
		in, out := &in.GroupByKeyPaths, &out.GroupByKeyPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupMemberDefinition.
func (in *PodGroupMemberDefinition) DeepCopy() *PodGroupMemberDefinition {
	if in == nil {
		return nil
	}
	out := new(PodGroupMemberDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelector) DeepCopyInto(out *PodSelector) {
	*out = *in
	if in.ComponentTypeSelector != nil {
		in, out := &in.ComponentTypeSelector, &out.ComponentTypeSelector
		*out = new(ComponentTypeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ComponentInstanceSelector != nil {
		in, out := &in.ComponentInstanceSelector, &out.ComponentInstanceSelector
		*out = new(ComponentInstanceSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelector.
func (in *PodSelector) DeepCopy() *PodSelector {
	if in == nil {
		return nil
	}
	out := new(PodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RIValidator) DeepCopyInto(out *RIValidator) {
	*out = *in
	if in.ri != nil {
		in, out := &in.ri, &out.ri
		*out = new(ResourceInterface)
		(*in).DeepCopyInto(*out)
	}
	in.rootComponent.DeepCopyInto(&out.rootComponent)
	if in.allComponents != nil {
		in, out := &in.allComponents, &out.allComponents
		*out = make(map[string]ComponentDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RIValidator.
func (in *RIValidator) DeepCopy() *RIValidator {
	if in == nil {
		return nil
	}
	out := new(RIValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInterface) DeepCopyInto(out *ResourceInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInterface.
func (in *ResourceInterface) DeepCopy() *ResourceInterface {
	if in == nil {
		return nil
	}
	out := new(ResourceInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInterfaceList) DeepCopyInto(out *ResourceInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInterfaceList.
func (in *ResourceInterfaceList) DeepCopy() *ResourceInterfaceList {
	if in == nil {
		return nil
	}
	out := new(ResourceInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInterfaceSpec) DeepCopyInto(out *ResourceInterfaceSpec) {
	*out = *in
	in.StructureDefinition.DeepCopyInto(&out.StructureDefinition)
	in.Instructions.DeepCopyInto(&out.Instructions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInterfaceSpec.
func (in *ResourceInterfaceSpec) DeepCopy() *ResourceInterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceInterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInterfaceStatus) DeepCopyInto(out *ResourceInterfaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInterfaceStatus.
func (in *ResourceInterfaceStatus) DeepCopy() *ResourceInterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceInterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDefinition) DeepCopyInto(out *ScaleDefinition) {
	*out = *in
	if in.ReplicasPath != nil {
		in, out := &in.ReplicasPath, &out.ReplicasPath
		*out = new(string)
		**out = **in
	}
	if in.MinReplicasPath != nil {
		in, out := &in.MinReplicasPath, &out.MinReplicasPath
		*out = new(string)
		**out = **in
	}
	if in.MaxReplicasPath != nil {
		in, out := &in.MaxReplicasPath, &out.MaxReplicasPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDefinition.
func (in *ScaleDefinition) DeepCopy() *ScaleDefinition {
	if in == nil {
		return nil
	}
	out := new(ScaleDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecDefinition) DeepCopyInto(out *SpecDefinition) {
	*out = *in
	if in.PodTemplateSpecPath != nil {
		in, out := &in.PodTemplateSpecPath, &out.PodTemplateSpecPath
		*out = new(string)
		**out = **in
	}
	if in.PodSpecPath != nil {
		in, out := &in.PodSpecPath, &out.PodSpecPath
		*out = new(string)
		**out = **in
	}
	if in.MetadataPath != nil {
		in, out := &in.MetadataPath, &out.MetadataPath
		*out = new(string)
		**out = **in
	}
	if in.FragmentedPodSpecDefinition != nil {
		in, out := &in.FragmentedPodSpecDefinition, &out.FragmentedPodSpecDefinition
		*out = new(FragmentedPodSpecDefinition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecDefinition.
func (in *SpecDefinition) DeepCopy() *SpecDefinition {
	if in == nil {
		return nil
	}
	out := new(SpecDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusDefinition) DeepCopyInto(out *StatusDefinition) {
	*out = *in
	if in.PhaseDefinition != nil {
		in, out := &in.PhaseDefinition, &out.PhaseDefinition
		*out = new(PhaseDefinition)
		**out = **in
	}
	if in.ConditionsDefinition != nil {
		in, out := &in.ConditionsDefinition, &out.ConditionsDefinition
		*out = new(ConditionsDefinition)
		(*in).DeepCopyInto(*out)
	}
	in.StatusMappings.DeepCopyInto(&out.StatusMappings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusDefinition.
func (in *StatusDefinition) DeepCopy() *StatusDefinition {
	if in == nil {
		return nil
	}
	out := new(StatusDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusMappings) DeepCopyInto(out *StatusMappings) {
	*out = *in
	if in.Initializing != nil {
		in, out := &in.Initializing, &out.Initializing
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Running != nil {
		in, out := &in.Running, &out.Running
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Completed != nil {
		in, out := &in.Completed, &out.Completed
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make([]StatusMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusMappings.
func (in *StatusMappings) DeepCopy() *StatusMappings {
	if in == nil {
		return nil
	}
	out := new(StatusMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusMatcher) DeepCopyInto(out *StatusMatcher) {
	*out = *in
	if in.ByConditions != nil {
		in, out := &in.ByConditions, &out.ByConditions
		*out = make([]ExpectedCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusMatcher.
func (in *StatusMatcher) DeepCopy() *StatusMatcher {
	if in == nil {
		return nil
	}
	out := new(StatusMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructureDefinition) DeepCopyInto(out *StructureDefinition) {
	*out = *in
	in.RootComponent.DeepCopyInto(&out.RootComponent)
	if in.ChildComponents != nil {
		in, out := &in.ChildComponents, &out.ChildComponents
		*out = make([]ComponentDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalChildKinds != nil {
		in, out := &in.AdditionalChildKinds, &out.AdditionalChildKinds
		*out = make([]GroupVersionKind, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructureDefinition.
func (in *StructureDefinition) DeepCopy() *StructureDefinition {
	if in == nil {
		return nil
	}
	out := new(StructureDefinition)
	in.DeepCopyInto(out)
	return out
}
