apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: argoproj-io-workflow-v1alpha1
spec:
  structureDefinition:
    rootComponent:
      name: workflow
      kind:
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
      scaleDefinition:
        replicasPath: .spec.parallelism
      specDefinition:
        metadataPath: spec.workflowMetadata
        fragmentedPodSpecDefinition:
          schedulerNamePath: .spec.schedulerName
          podAffinityPath: .spec.affinity.podAffinity
          nodeAffinityPath: .spec.affinity.nodeAffinity
      statusDefinition:
        phaseDefinition:
          path: .status.phase
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          running:
          - byPhase: Running
          completed:
          - byPhase: Succeeded
          failed:
          - byPhase: Failed
          - byPhase: Error
    childComponents:
      - name: templates[].name
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: workflow
        specDefinition:
          metadataPath: spec.templates[].metadata
          fragmentedPodSpecDefinition:
            schedulerNamePath: spec.templates[].schedulerName
            labelsPath: spec.templates[].metadata.labels
            annotationsPath: spec.templates[].metadata.annotations
            priorityClassNamePath: spec.templates[].priorityClassName
            podAffinityPath: spec.templates[].affinity.podAffinity
            nodeAffinityPath: spec.templates[].affinity.nodeAffinity
        scaleDefinition:
          replicasPath: .spec.templates[].parallelism
