apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: batch-v1-job
spec:
  structureDefinition:
    rootComponent:
      kind:
        group: batch
        kind: Job
        version: v1
      name: job
      scaleDefinition:
        replicasPath: .spec.parallelism // 1
      specDefinition:
        podTemplateSpecPath: .spec.template
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          reasonFieldName: reason
          statusFieldName: status
          typeFieldName: type
        statusMappings:
          completed:
            - byConditions:
                - status: "True"
                  type: Complete
          failed:
            - byConditions:
                - status: "True"
                  type: Failed
          initializing:
            - byExpression:
                expectedResult: "true"
                expression: (.status.active // 0) > 0 and (.status.ready // 0) == 0
          running:
            - byExpression:
                expectedResult: "true"
                expression: (.status.active // 0) > 0 and (.status.ready // 0) > 0
          degraded:
            - byExpression:
                expression: ".spec.parallelism > 1 and (.status.ready // 0) < .spec.parallelism and ((.status.succeeded // 0) > 0 or (.status.failed // 0) > 0)"
                expectedResult: "true"
          suspended:
            - byConditions:
                - status: "True"
                  type: Suspended
          suspending:
            - byConditions:
                - status: "False"
                  type: Suspended
              byExpression:
                expectedResult: "true"
                expression: .spec.suspend == true and (.status.ready // 0) > 0
      suspendDefinition:
        resumeActions:
          - path: .spec.suspend
            value: "false"
        suspendActions:
          - path: .spec.suspend
            value: "true"
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - name: job
        members:
        - componentName: job
          groupByKeyPaths:
          - .metadata.labels["batch.kubernetes.io/job-name"]
