apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: apps-deployment-v1
spec:
  structureDefinition:
    rootComponent:
      name: deployment
      kind:
        group: apps
        version: v1
        kind: Deployment
      scaleDefinition:
        replicasPath: .spec.replicas // 1
      specDefinition:
        podTemplateSpecPath: .spec.template
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          initializing:
          - byConditions:
              - type: Progressing
                status: "True"
              - type: Available
                status: "False"
          running:
          - byConditions:
              - type: Progressing
                status: "True"
                reason: NewReplicaSetAvailable
          failed:
          - byConditions:
              - type: Progressing
                status: "False"
                reason: ProgressDeadlineExceeded
    childComponents:
      - name: replicaset
        kind:
          group: apps
          version: v1
          kind: ReplicaSet
        ownerRef: deployment
