apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: nvidia-com-dynamographdeployment-v1beta1
spec:
  structureDefinition:
    rootComponent:
      name: dynamographdeployment
      kind:
        group: nvidia.com
        version: v1beta1
        kind: DynamoGraphDeployment
      statusDefinition:
        phaseDefinition:
          path: .status.state
        statusMappings:
          initializing:
          - byPhase: initializing
          - byPhase: pending
          running:
          - byPhase: successful
          failed:
          - byPhase: failed
    childComponents:
      - name: component
        ownerRef: dynamographdeployment
        specDefinition:
          fragmentedPodSpecDefinition:
            schedulerNamePath: .spec.components[] | .podTemplate.spec.schedulerName
            labelsPath: .spec.components[] | .podTemplate.metadata.labels
            annotationsPath: .spec.components[] | .podTemplate.metadata.annotations
            resourceClaimsPath: .spec.components[] | .podTemplate.spec.resourceClaims
            podAffinityPath: .spec.components[] | .podTemplate.spec.affinity.podAffinity
            nodeAffinityPath: .spec.components[] | .podTemplate.spec.affinity.nodeAffinity
            containerPath: .spec.components[] | .podTemplate.spec.containers[] | select(.name == "main")
            imagePath: .spec.components[] | .podTemplate.spec.containers[] | select(.name == "main") | .image
            priorityClassNamePath: .spec.components[] | .podTemplate.spec.priorityClassName
        scaleDefinition:
          replicasPath: .spec.components[] | (.replicas // 1) * (.multinode.nodeCount // 1)
        instanceIdPath: .spec.components[] | .name
        podSelector:
          componentInstanceSelector:
            idPath: .metadata.labels["nvidia.com/dynamo-component"]
          replicaSelector:
            keyPath: .metadata.labels["grove.io/podcliquescalinggroup-replica-index"] // .metadata.labels["leaderworkerset.sigs.k8s.io/group-index"]
    additionalChildKinds:
      - group: nvidia.com
        version: v1beta1
        kind: DynamoComponentDeployment
      - group: leaderworkerset.x-k8s.io
        version: v1
        kind: LeaderWorkerSet
      - group: scheduler.grove.io
        version: v1alpha1
        kind: PodGang
      - group: grove.io
        version: v1alpha1
        kind: PodClique
      - group: grove.io
        version: v1alpha1
        kind: PodCliqueSet
      - group: grove.io
        version: v1alpha1
        kind: PodCliqueScalingGroup
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: component
          members:
            - componentName: component
              groupByKeyPaths:
                - .metadata.labels["nvidia.com/dynamo-component"] | ascii_downcase
