apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: jobset-x-k8s-io-v1alpha2-jobset
spec:
  structureDefinition:
    rootComponent:
      name: jobset
      kind:
        group: jobset.x-k8s.io
        version: v1alpha2
        kind: JobSet
      suspendDefinition:
        suspendActions:
          - path: .spec.suspend
            value: "true"
        resumeActions:
          - path: .spec.suspend
            value: "false"
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
          reasonFieldName: reason
        statusMappings:
          initializing:
          - byExpression:
              # Some replicatedJobs are active but none are ready yet
              expression: ".status.replicatedJobsStatus | any(.active > 0 and .ready < 0) and all(.failed == 0)"
              expectedResult: "true"
          running:
          - byExpression:
              # Total ready across all replicatedJobs equals total expected replicas
              expression: ".status.replicatedJobsStatus | any(.ready > 0 and .active > 0) and all(.failed == 0)"
              expectedResult: "true"
          completed:
          - byConditions:
            - type: Completed
              status: "True"
          failed:
          - byConditions:
            - type: Failed
              status: "True"
          suspended:
          - byConditions:
            - type: Suspended
              status: "True"

    childComponents:
    # ReplicatedJob - represents the actual Job resources created by JobSet
    - name: replicatedjob
      kind:
        group: batch
        version: v1
        kind: Job
      ownerRef: jobset
      specDefinition:
        podTemplateSpecPath: .spec.replicatedJobs[].template.spec.template
      scaleDefinition:
        # Total pods per replicatedJob = replicas (Job instances) * parallelism (pods per Job)
        replicasPath: .spec.replicatedJobs[] | .replicas * .template.spec.parallelism
      instanceIdPath: .spec.replicatedJobs[].name
      podSelector:
        componentInstanceSelector:
          idPath: .metadata.labels["jobset.sigs.k8s.io/replicatedjob-name"]

  optimizationInstructions:
    gangScheduling:
      podGroups:
      - name: job
        members:
        - componentName: replicatedjob
          groupByKeyPaths:
          - .metadata.labels["jobset.sigs.k8s.io/replicatedjob-name"]
