apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: kubevirt-io-virtualmachineinstance-v1
spec:
  structureDefinition:
    rootComponent:
      name: virtualmachineinstance
      kind:
        group: kubevirt.io
        version: v1
        kind: VirtualMachineInstance
      scaleDefinition:
        replicasPath: "1"
      specDefinition:
        metadataPath: metadata
        fragmentedPodSpecDefinition:
          schedulerNamePath: spec.schedulerName
          priorityClassNamePath: spec.priorityClassName
          resourcesPath: spec.domain.resources
          podAffinityPath: spec.affinity.podAffinity
          nodeAffinityPath: spec.affinity.nodeAffinity
      statusDefinition:
        phaseDefinition:
          path: .status.phase
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          initializing:
          - byPhase: Scheduled
          running:
          - byPhase: Running
          completed:
          - byPhase: Succeeded
          failed:
          - byPhase: Failed
