apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: apps-nvidia-com-nimcache-v1alpha1
spec:
  structureDefinition:
    rootComponent:
      name: nimcache
      kind:
        group: apps.nvidia.com
        version: v1alpha1
        kind: NIMCache
      scaleDefinition:
        replicasPath: "1"
      specDefinition:
        fragmentedPodSpecDefinition:
          resourcesPath: '{requests: .spec.resources}'
      statusDefinition:
        phaseDefinition:
          path: .status.state
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          initializing:
          - byPhase: Pending
          - byPhase: NotReady
          - byPhase: PVC-Created
          - byPhase: Started
          - byConditions:
              - type: NIM_CACHE_JOB_CREATED
                status: "True"
          running:
          - byPhase: InProgress
          completed:
          - byPhase: Ready
            byConditions:
              - type: NIM_CACHE_JOB_COMPLETED
                status: "True"
          failed:
          - byPhase: Failed
