apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: ray-io-rayservice-v1
spec:
  structureDefinition:
    rootComponent:
      name: rayservice
      kind:
        group: ray.io
        version: v1
        kind: RayService
      statusDefinition:
        phaseDefinition:
          path: .status.state
        statusMappings:
          running:
          - byPhase: ready
          failed:
          - byPhase: failed
    childComponents:
      - name: head
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: rayservice
        specDefinition:
          podTemplateSpecPath: .spec.rayClusterSpec.headGroupSpec.template
        scaleDefinition:
          replicasPath: "1"
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["ray.io/node-type"]
            value: head
      - name: worker
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: rayservice
        specDefinition:
          podTemplateSpecPath: .spec.rayClusterSpec.workerGroupSpecs[].template
        scaleDefinition:
          replicasPath: .spec.rayClusterSpec.workerGroupSpecs[].replicas // 1
        instanceIdPath: .spec.rayClusterSpec.workerGroupSpecs[].groupName
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["ray.io/node-type"]
            value: worker
          componentInstanceSelector:
            idPath: .metadata.labels["ray.io/group"]
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: service
          members:
            - componentName: head
              groupByKeyPaths:
                - .metadata.labels["ray.io/cluster"]
            - componentName: worker
              groupByKeyPaths:
                - .metadata.labels["ray.io/cluster"]
