apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: machinelearning-seldon-io-seldondeployment-v1
spec:
  structureDefinition:
    rootComponent:
      name: seldondeployment
      kind:
        group: machinelearning.seldon.io
        version: v1
        kind: SeldonDeployment
      scaleDefinition:
        replicasPath: .spec.replicas
      statusDefinition:
        phaseDefinition:
          path: .status.state
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          initializing:
          - byPhase: Creating
          running:
          - byPhase: Available
          failed:
          - byPhase: Failed
    childComponents:
      - name: component
        ownerRef: seldondeployment
        specDefinition:
          podSpecPath: .spec.predictors[].componentSpecs[].spec
          metadataPath: .spec.predictors[].componentSpecs[].metadata
        scaleDefinition:
          replicasPath: .spec.predictors[].componentSpecs[].replicas
          minReplicasPath: .spec.predictors[].componentSpecs[].hpaSpec.minReplicas
          maxReplicasPath: .spec.predictors[].componentSpecs[].hpaSpec.maxReplicas
        instanceIdPath: .spec.predictors[] | .name as $pname | .componentSpecs | to_entries[] | "\($pname)-\(.key)"
        podSelector:
          componentInstanceSelector:
            idPath: .metadata.labels["version"] as $predicator | .metadata.labels["app"] | split($predicator + "-")[1] | split("-")[0] as $component_index | "\($predicator)-\($component_index)"
