apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: slinky-slurm-net-nodeset-v1beta1
spec:
  structureDefinition:
    rootComponent:
      name: nodeset
      kind:
        group: slinky.slurm.net
        version: v1beta1
        kind: NodeSet
      scaleDefinition:
        replicasPath: .spec.replicas
      specDefinition:
        fragmentedPodSpecDefinition:
          schedulerNamePath: .spec.template.spec.schedulerName
          labelsPath: .spec.template.metadata.labels
          annotationsPath: .spec.template.metadata.annotations
          resourcesPath: (.spec.slurmd.resources // .spec.template.spec.containers[0].resources)
          priorityClassNamePath: .spec.template.spec.priorityClassName
          podAffinityPath: .spec.template.spec.affinity.podAffinity
          nodeAffinityPath: .spec.template.spec.affinity.nodeAffinity
          containerPath: (.spec.slurmd // .spec.template.spec.containers[0])
          imagePath: (.spec.slurmd.image // .spec.template.spec.containers[0].image)
      statusDefinition:
        statusMappings:
          initializing:
          - byExpression:
              expression: (.status.replicas // 0) > 0 and (.status.readyReplicas // 0) == 0
              expectedResult: "true"
          running:
          - byExpression:
              expression: (.status.readyReplicas // 0) > 0
              expectedResult: "true"
      podSelector:
        componentTypeSelector:
          keyPath: .metadata.labels["app.kubernetes.io/name"]
          value: slurmd
