apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: tekton-dev-taskrun-v1
spec:
  structureDefinition:
    rootComponent:
      name: taskrun
      kind:
        group: tekton.dev
        version: v1
        kind: TaskRun
      scaleDefinition:
        replicasPath: "1"
      specDefinition:
        podTemplateSpecPath: .spec.podTemplate
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          initializing:
          - byConditions:
              - type: Succeeded
                status: Unknown
                reason: Started
          running:
          - byConditions:
              - type: Succeeded
                status: Unknown
                reason: Running
          completed:
          - byConditions:
              - type: Succeeded
                status: "True"
          failed:
          - byConditions:
              - type: Succeeded
                status: "False"
