apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: kubeflow-org-tfjob-v1
spec:
  structureDefinition:
    rootComponent:
      name: tfjob
      kind:
        group: kubeflow.org
        version: v1
        kind: TFJob
      suspendDefinition:
        suspendActions:
          - path: .spec.runPolicy.suspend
            value: "true"
        resumeActions:
          - path: .spec.runPolicy.suspend
            value: "false"
      statusDefinition:
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          reasonFieldName: reason
          messageFieldName: message
        statusMappings:
          initializing:
          - byConditions:
              - type: Created
                status: "True"
          running:
          - byConditions:
              - type: Running
                status: "True"
          completed:
          - byConditions:
              - type: Succeeded
                status: "True"
          failed:
          - byConditions:
              - type: Failed
                status: "True"
          suspended:
          - byConditions:
              - type: Suspended
                status: "True"
          suspending:
          - byExpression:
              expression: .spec.runPolicy.suspend == true and (.status.replicaStatuses // {} | to_entries | map(.value.active // 0) | add // 0) > 0
              expectedResult: "true"
    childComponents:
      - name: Chief
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: tfjob
        specDefinition:
          podTemplateSpecPath: .spec.tfReplicaSpecs.Chief.template
        scaleDefinition:
          replicasPath: .spec.tfReplicaSpecs.Chief.replicas // 1
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["training.kubeflow.org/replica-type"]
            value: Chief
      - name: Worker
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: tfjob
        specDefinition:
          podTemplateSpecPath: .spec.tfReplicaSpecs.Worker.template
        scaleDefinition:
          replicasPath: .spec.tfReplicaSpecs.Worker.replicas // 1
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["training.kubeflow.org/replica-type"]
            value: Worker
      - name: PS
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: tfjob
        specDefinition:
          podTemplateSpecPath: .spec.tfReplicaSpecs.PS.template
        scaleDefinition:
          replicasPath: .spec.tfReplicaSpecs.PS.replicas // 1
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["training.kubeflow.org/replica-type"]
            value: PS
      - name: Evaluator
        kind:
          group: ""
          version: v1
          kind: Pod
        ownerRef: tfjob
        specDefinition:
          podTemplateSpecPath: .spec.tfReplicaSpecs.Evaluator.template
        scaleDefinition:
          replicasPath: .spec.tfReplicaSpecs.Evaluator.replicas // 1
        podSelector:
          componentTypeSelector:
            keyPath: .metadata.labels["training.kubeflow.org/replica-type"]
            value: Evaluator
  optimizationInstructions:
    gangScheduling:
      podGroups:
        - name: job
          members:
            - componentName: Chief
              groupByKeyPaths:
                - .metadata.labels["training.kubeflow.org/job-name"]
            - componentName: Worker
              groupByKeyPaths:
                - .metadata.labels["training.kubeflow.org/job-name"]
            - componentName: PS
              groupByKeyPaths:
                - .metadata.labels["training.kubeflow.org/job-name"]
            - componentName: Evaluator
              groupByKeyPaths:
                - .metadata.labels["training.kubeflow.org/job-name"]
