// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=runner_mock.go -package=jq Runner
//

// Package jq is a generated GoMock package.
package jq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExtractor is a mock of Extractor interface.
type MockExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorMockRecorder
	isgomock struct{}
}

// MockExtractorMockRecorder is the mock recorder for MockExtractor.
type MockExtractorMockRecorder struct {
	mock *MockExtractor
}

// NewMockExtractor creates a new mock instance.
func NewMockExtractor(ctrl *gomock.Controller) *MockExtractor {
	mock := &MockExtractor{ctrl: ctrl}
	mock.recorder = &MockExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractor) EXPECT() *MockExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockExtractor) Extract(ctx context.Context, expression string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, expression)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockExtractorMockRecorder) Extract(ctx, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockExtractor)(nil).Extract), ctx, expression)
}

// MockAssigner is a mock of Assigner interface.
type MockAssigner struct {
	ctrl     *gomock.Controller
	recorder *MockAssignerMockRecorder
	isgomock struct{}
}

// MockAssignerMockRecorder is the mock recorder for MockAssigner.
type MockAssignerMockRecorder struct {
	mock *MockAssigner
}

// NewMockAssigner creates a new mock instance.
func NewMockAssigner(ctrl *gomock.Controller) *MockAssigner {
	mock := &MockAssigner{ctrl: ctrl}
	mock.recorder = &MockAssignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssigner) EXPECT() *MockAssignerMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockAssigner) Assign(ctx context.Context, expression string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, expression, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MockAssignerMockRecorder) Assign(ctx, expression, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockAssigner)(nil).Assign), ctx, expression, value)
}

// AssignZip mocks base method.
func (m *MockAssigner) AssignZip(ctx context.Context, expression string, values []any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignZip", ctx, expression, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignZip indicates an expected call of AssignZip.
func (mr *MockAssignerMockRecorder) AssignZip(ctx, expression, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignZip", reflect.TypeOf((*MockAssigner)(nil).AssignZip), ctx, expression, values)
}

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockRunner) Assign(ctx context.Context, expression string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, expression, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MockRunnerMockRecorder) Assign(ctx, expression, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockRunner)(nil).Assign), ctx, expression, value)
}

// AssignZip mocks base method.
func (m *MockRunner) AssignZip(ctx context.Context, expression string, values []any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignZip", ctx, expression, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignZip indicates an expected call of AssignZip.
func (mr *MockRunnerMockRecorder) AssignZip(ctx, expression, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignZip", reflect.TypeOf((*MockRunner)(nil).AssignZip), ctx, expression, values)
}

// Extract mocks base method.
func (m *MockRunner) Extract(ctx context.Context, expression string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, expression)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockRunnerMockRecorder) Extract(ctx, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockRunner)(nil).Extract), ctx, expression)
}

// GetObject mocks base method.
func (m *MockRunner) GetObject() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockRunnerMockRecorder) GetObject() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockRunner)(nil).GetObject))
}
