// Code generated by MockGen. DO NOT EDIT.
// Source: evaluator.go
//
// Generated by this command:
//
//	mockgen -source=evaluator.go -destination=evaluator_mock.go -package=query QueryEvaluator
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQueryEvaluator is a mock of QueryEvaluator interface.
type MockQueryEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockQueryEvaluatorMockRecorder
	isgomock struct{}
}

// MockQueryEvaluatorMockRecorder is the mock recorder for MockQueryEvaluator.
type MockQueryEvaluatorMockRecorder struct {
	mock *MockQueryEvaluator
}

// NewMockQueryEvaluator creates a new mock instance.
func NewMockQueryEvaluator(ctrl *gomock.Controller) *MockQueryEvaluator {
	mock := &MockQueryEvaluator{ctrl: ctrl}
	mock.recorder = &MockQueryEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryEvaluator) EXPECT() *MockQueryEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockQueryEvaluator) Evaluate(ctx context.Context, expression string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, expression)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockQueryEvaluatorMockRecorder) Evaluate(ctx, expression any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockQueryEvaluator)(nil).Evaluate), ctx, expression)
}
