# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
kind: Karta
apiVersion: run.ai/v1alpha1
metadata:
  name: apps-nvidia-com-nimcache-v1alpha1
spec:
  structureDefinition:
    rootComponent:
      name: nimcache
      kind:
        group: apps.nvidia.com
        version: v1alpha1
        kind: NIMCache
      specDefinition:
        fragmentedPodSpecDefinition:
          resourcesPath: '{requests: .spec.resources}'
      scaleDefinition:
        replicasPath: "1"
      statusDefinition:
        phaseDefinition:
          path: .status.state
        conditionsDefinition:
          path: .status.conditions
          typeFieldName: type
          statusFieldName: status
          messageFieldName: message
          reasonFieldName: reason
        statusMappings:
          initializing:
            - byPhase: Pending
            - byPhase: NotReady
            - byPhase: PVC-Created
            - byPhase: Started
            - byConditions:
                - type: NIM_CACHE_JOB_CREATED
                  status: "True"
          running:
            - byPhase: InProgress
          completed:
            - byPhase: Ready
              byConditions:
                - type: NIM_CACHE_JOB_COMPLETED
                  status: "True"
          failed:
            - byPhase: Failed
  optimizationInstructions: {}
