# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: apps-nvidia-com-nimcache-v1alpha1
spec:
  optimizationInstructions: {}
  structureDefinition:
    rootComponent:
      kind:
        group: apps.nvidia.com
        kind: NIMCache
        version: v1alpha1
      name: nimcache
      scaleDefinition:
        replicasPath: "1"
      specDefinition:
        fragmentedPodSpecDefinition:
          resourcesPath: '{requests: .spec.resources}'
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          reasonFieldName: reason
          statusFieldName: status
          typeFieldName: type
        phaseDefinition:
          path: .status.state
        statusMappings:
          completed:
          - byConditions:
            - status: "True"
              type: NIM_CACHE_JOB_COMPLETED
            byPhase: Ready
          failed:
          - byPhase: Failed
          initializing:
          - byPhase: Pending
          - byPhase: NotReady
          - byPhase: PVC-Created
          - byPhase: Started
          - byConditions:
            - status: "True"
              type: NIM_CACHE_JOB_CREATED
          running:
          - byPhase: InProgress
status: {}
