# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: batch-job-v1
spec:
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - members:
        - componentName: job
          groupByKeyPaths:
          - .metadata.labels["batch.kubernetes.io/job-name"]
        name: job
  structureDefinition:
    rootComponent:
      kind:
        group: batch
        kind: Job
        version: v1
      name: job
      scaleDefinition:
        replicasPath: .spec.parallelism // 1
      specDefinition:
        podTemplateSpecPath: .spec.template
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          reasonFieldName: reason
          statusFieldName: status
          typeFieldName: type
        statusMappings:
          completed:
          - byConditions:
            - status: "True"
              type: Complete
          degraded:
          - byExpression:
              expectedResult: "true"
              expression: .spec.parallelism > 1 and (.status.ready // 0) < .spec.parallelism
                and ((.status.succeeded // 0) > 0 or (.status.failed // 0) > 0)
          failed:
          - byConditions:
            - status: "True"
              type: Failed
          initializing:
          - byExpression:
              expectedResult: "true"
              expression: (.status.active // 0) > 0 and (.status.ready // 0) == 0
          running:
          - byExpression:
              expectedResult: "true"
              expression: (.status.active // 0) > 0 and (.status.ready // 0) > 0
          suspended:
          - byConditions:
            - status: "True"
              type: Suspended
      suspendDefinition:
        resumeActions:
        - path: .spec.suspend
          value: "false"
        suspendActions:
        - path: .spec.suspend
          value: "true"
