# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: batch-cronjob-v1
spec:
  optimizationInstructions: {}
  structureDefinition:
    childComponents:
    - kind:
        group: batch
        kind: Job
        version: v1
      name: job
      ownerRef: cronjob
    rootComponent:
      kind:
        group: batch
        kind: CronJob
        version: v1
      name: cronjob
      scaleDefinition:
        replicasPath: .spec.jobTemplate.spec.parallelism // 1
      specDefinition:
        podTemplateSpecPath: .spec.jobTemplate.spec.template
      statusDefinition:
        statusMappings:
          initializing:
          - byExpression:
              expectedResult: "true"
              expression: (.spec.suspend // false) != true and (.status.lastScheduleTime
                == null)
          running:
          - byExpression:
              expectedResult: "true"
              expression: (.spec.suspend // false) != true and (.status.lastScheduleTime
                != null)
          suspended:
          - byExpression:
              expectedResult: "true"
              expression: (.spec.suspend // false) == true
      suspendDefinition:
        resumeActions:
        - path: .spec.suspend
          value: "false"
        suspendActions:
        - path: .spec.suspend
          value: "true"
