# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: grove-io-podcliqueset-v1alpha1
spec:
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - members:
        - componentName: clique
          groupByKeyPaths:
          - .metadata.labels["app.kubernetes.io/part-of"]
          - .metadata.labels["grove.io/podcliqueset-replica-index"]
        - componentName: scalinggroup
          groupByKeyPaths:
          - .metadata.labels["app.kubernetes.io/part-of"]
          - .metadata.labels["grove.io/podcliqueset-replica-index"]
        name: podcliqueset-replica
  structureDefinition:
    additionalChildKinds:
    - group: grove.io
      kind: PodClique
      version: v1alpha1
    - group: grove.io
      kind: PodCliqueScalingGroup
      version: v1alpha1
    - group: scheduler.grove.io
      kind: PodGang
      version: v1alpha1
    childComponents:
    - instanceIdPath: .spec.template as $t | $t.cliques[] | select(.name as $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?]
        | index($n) | not)) | .name
      kind:
        group: grove.io
        kind: PodClique
        version: v1alpha1
      name: clique
      ownerRef: podcliqueset
      podSelector:
        componentInstanceSelector:
          idPath: .metadata.labels["grove.io/podclique"]
        replicaSelector:
          keyPath: .metadata.labels["grove.io/podcliqueset-replica-index"]
      scaleDefinition:
        maxReplicasPath: .spec.template as $t | $t.cliques[] | select(.name as $n
          | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not)) | .spec.autoScalingConfig.maxReplicas
        minReplicasPath: .spec.template as $t | $t.cliques[] | select(.name as $n
          | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not)) | .spec.autoScalingConfig.minReplicas
        replicasPath: .spec.replicas as $r | .spec.template as $t | $t.cliques[] |
          select(.name as $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n)
          | not)) | (($r // 1) * (.spec.replicas // 1))
      specDefinition:
        fragmentedPodSpecDefinition:
          annotationsPath: .spec.template as $t | $t.cliques[] | select(.name as $n
            | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not)) |
            .annotations
          containersPath: .spec.template as $t | $t.cliques[] | select(.name as $n
            | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not)) |
            .spec.podSpec.containers
          labelsPath: .spec.template as $t | $t.cliques[] | select(.name as $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?]
            | index($n) | not)) | .labels
          nodeAffinityPath: .spec.template as $t | $t.cliques[] | select(.name as
            $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not))
            | .spec.podSpec.affinity.nodeAffinity
          podAffinityPath: .spec.template as $t | $t.cliques[] | select(.name as $n
            | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not)) |
            .spec.podSpec.affinity.podAffinity
          priorityClassNamePath: .spec.template as $t | $t.cliques[] | select(.name
            as $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not))
            | .spec.podSpec.priorityClassName
          resourceClaimsPath: .spec.template as $t | $t.cliques[] | select(.name as
            $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not))
            | .spec.podSpec.resourceClaims
          schedulerNamePath: .spec.template as $t | $t.cliques[] | select(.name as
            $n | ([$t.podCliqueScalingGroups[]?.cliqueNames[]?] | index($n) | not))
            | .spec.podSpec.schedulerName
    - instanceIdPath: .spec.template.podCliqueScalingGroups[].name
      kind:
        group: grove.io
        kind: PodCliqueScalingGroup
        version: v1alpha1
      name: scalinggroup
      ownerRef: podcliqueset
      podSelector:
        componentInstanceSelector:
          idPath: .metadata.labels["grove.io/podcliquescalinggroup"]
        replicaSelector:
          keyPath: .metadata.labels["grove.io/podcliquescalinggroup-replica-index"]
      scaleDefinition:
        maxReplicasPath: .spec.template.podCliqueScalingGroups[].scaleConfig.maxReplicas
        minReplicasPath: .spec.template.podCliqueScalingGroups[].scaleConfig.minReplicas
        replicasPath: (.spec.replicas // 1) * (.spec.template.podCliqueScalingGroups[].replicas
          // 1)
    rootComponent:
      kind:
        group: grove.io
        kind: PodCliqueSet
        version: v1alpha1
      name: podcliqueset
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          reasonFieldName: reason
          statusFieldName: status
          typeFieldName: type
        statusMappings:
          failed:
          - byConditions:
            - status: "True"
              type: TopologyLevelsUnavailable
          initializing:
          - byExpression:
              expectedResult: "true"
              expression: (.spec.replicas // 0) > 0 and (.status.availableReplicas
                // 0) < (.spec.replicas // 0)
          running:
          - byExpression:
              expectedResult: "true"
              expression: (.status.availableReplicas // 0) >= (.spec.replicas // 0)
