# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: kubeflow-org-mpijob-v2beta1
spec:
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - members:
        - componentName: launcher
          groupByKeyPaths:
          - .metadata.labels["training.kubeflow.org/job-name"]
        - componentName: worker
          groupByKeyPaths:
          - .metadata.labels["training.kubeflow.org/job-name"]
        name: job
  structureDefinition:
    childComponents:
    - kind:
        group: ""
        kind: Pod
        version: v1
      name: launcher
      ownerRef: mpijob
      podSelector:
        componentTypeSelector:
          keyPath: .metadata.labels["training.kubeflow.org/job-role"]
          value: launcher
      scaleDefinition:
        replicasPath: .spec.mpiReplicaSpecs.Launcher.replicas // 1
      specDefinition:
        podTemplateSpecPath: .spec.mpiReplicaSpecs.Launcher.template
    - kind:
        group: ""
        kind: Pod
        version: v1
      name: worker
      ownerRef: mpijob
      podSelector:
        componentTypeSelector:
          keyPath: .metadata.labels["training.kubeflow.org/job-role"]
          value: worker
      scaleDefinition:
        replicasPath: .spec.mpiReplicaSpecs.Worker.replicas // 1
      specDefinition:
        podTemplateSpecPath: .spec.mpiReplicaSpecs.Worker.template
    rootComponent:
      kind:
        group: kubeflow.org
        kind: MPIJob
        version: v2beta1
      name: mpijob
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          reasonFieldName: reason
          statusFieldName: status
          typeFieldName: type
        statusMappings:
          completed:
          - byConditions:
            - status: "True"
              type: Succeeded
          failed:
          - byConditions:
            - status: "True"
              type: Failed
          initializing:
          - byConditions:
            - status: "True"
              type: Created
          running:
          - byConditions:
            - status: "True"
              type: Running
          suspended:
          - byConditions:
            - status: "True"
              type: Suspended
      suspendDefinition:
        resumeActions:
        - path: .spec.runPolicy.suspend
          value: "false"
        suspendActions:
        - path: .spec.runPolicy.suspend
          value: "true"
