# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: kubeflow-org-pytorchjob-v1
spec:
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - members:
        - componentName: master
          groupByKeyPaths:
          - .metadata.labels["training.kubeflow.org/job-name"]
        - componentName: worker
          groupByKeyPaths:
          - .metadata.labels["training.kubeflow.org/job-name"]
        name: job
  structureDefinition:
    childComponents:
    - kind:
        group: ""
        kind: Pod
        version: v1
      name: master
      ownerRef: pytorchjob
      podSelector:
        componentTypeSelector:
          keyPath: .metadata.labels["training.kubeflow.org/replica-type"]
          value: master
      scaleDefinition:
        replicasPath: .spec.pytorchReplicaSpecs.Master.replicas // 1
      specDefinition:
        podTemplateSpecPath: .spec.pytorchReplicaSpecs.Master.template
    - kind:
        group: ""
        kind: Pod
        version: v1
      name: worker
      ownerRef: pytorchjob
      podSelector:
        componentTypeSelector:
          keyPath: .metadata.labels["training.kubeflow.org/replica-type"]
          value: worker
      scaleDefinition:
        maxReplicasPath: .spec.elasticPolicy.maxReplicas
        minReplicasPath: .spec.elasticPolicy.minReplicas
        replicasPath: .spec.pytorchReplicaSpecs.Worker.replicas // 1
      specDefinition:
        podTemplateSpecPath: .spec.pytorchReplicaSpecs.Worker.template
    rootComponent:
      kind:
        group: kubeflow.org
        kind: PyTorchJob
        version: v1
      name: pytorchjob
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          reasonFieldName: null
          statusFieldName: status
          typeFieldName: type
        statusMappings:
          completed:
          - byConditions:
            - status: "True"
              type: Succeeded
          failed:
          - byConditions:
            - status: "True"
              type: Failed
          initializing:
          - byConditions:
            - status: "True"
              type: Created
          running:
          - byConditions:
            - status: "True"
              type: Running
          suspended:
          - byConditions:
            - status: "True"
              type: Suspended
      suspendDefinition:
        resumeActions:
        - path: .spec.runPolicy.suspend
          value: "false"
        suspendActions:
        - path: .spec.runPolicy.suspend
          value: "true"
status: {}
