# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: nvidia-com-dynamographdeployment-v1alpha1
spec:
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - members:
        - componentName: service
          groupByKeyPaths:
          - .metadata.labels["nvidia.com/dynamo-component"]
        name: service
  structureDefinition:
    additionalChildKinds:
    - group: nvidia.com
      kind: DynamoComponentDeployment
      version: v1alpha1
    - group: leaderworkerset.x-k8s.io
      kind: LeaderWorkerSet
      version: v1
    - group: scheduler.grove.io
      kind: PodGang
      version: v1alpha1
    - group: grove.io
      kind: PodClique
      version: v1alpha1
    - group: grove.io
      kind: PodCliqueSet
      version: v1alpha1
    - group: grove.io
      kind: PodCliqueScalingGroup
      version: v1alpha1
    childComponents:
    - instanceIdPath: .spec.services | to_entries[] | .key
      name: service
      ownerRef: dynamographdeployment
      podSelector:
        componentInstanceSelector:
          idPath: .metadata.labels["nvidia.com/dynamo-component"]
        replicaSelector:
          keyPath: .metadata.labels["grove.io/podcliquescalinggroup-replica-index"]
            // .metadata.labels["leaderworkerset.sigs.k8s.io/group-index"]
      scaleDefinition:
        maxReplicasPath: .spec.services | .[] | .autoscaling.maxReplicas
        minReplicasPath: .spec.services | .[] | .autoscaling.minReplicas
        replicasPath: .spec.services[] | (.replicas // 1)
      specDefinition:
        fragmentedPodSpecDefinition:
          annotationsPath: .spec.services | .[] | .annotations
          containerPath: .spec.services | .[] | .extraPodSpec.mainContainer
          imagePath: .spec.services | .[] | .extraPodSpec.mainContainer.image
          labelsPath: .spec.services | .[] | .labels
          nodeAffinityPath: .spec.services | .[] | .extraPodSpec.affinity.nodeAffinity
          podAffinityPath: .spec.services | .[] | .extraPodSpec.affinity.podAffinity
          priorityClassNamePath: .spec.services | .[] | .extraPodSpec.priorityClassName
          resourceClaimsPath: .spec.services | .[] | .extraPodSpec.resourceClaims
          resourcesPath: .spec.services | .[] | .resources
          schedulerNamePath: .spec.services | .[] | .extraPodSpec.schedulerName
    rootComponent:
      kind:
        group: nvidia.com
        kind: DynamoGraphDeployment
        version: v1alpha1
      name: dynamographdeployment
      statusDefinition:
        phaseDefinition:
          path: .status.state
        statusMappings:
          failed:
          - byPhase: failed
          initializing:
          - byPhase: initializing
          - byPhase: pending
          running:
          - byPhase: successful
