# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation
apiVersion: run.ai/v1alpha1
kind: Karta
metadata:
  name: serving-knative-dev-service-v1
spec:
  optimizationInstructions:
    gangScheduling:
      podGroups:
      - members:
        - componentName: revision
          groupByKeyPaths:
          - .metadata.labels["serving.knative.dev/revision"]
        name: revision
  structureDefinition:
    additionalChildKinds:
    - group: apps
      kind: Deployment
      version: v1
    childComponents:
    - kind:
        group: serving.knative.dev
        kind: Revision
        version: v1
      name: revision
      ownerRef: knativeservice
      podSelector:
        componentTypeSelector:
          keyPath: .metadata.labels["serving.knative.dev/revision"]
    rootComponent:
      kind:
        group: serving.knative.dev
        kind: Service
        version: v1
      name: knativeservice
      scaleDefinition:
        maxReplicasPath: .spec.template.metadata.annotations["autoscaling.knative.dev/max-scale"]
        minReplicasPath: .spec.template.metadata.annotations["autoscaling.knative.dev/min-scale"]
          // 1
      specDefinition:
        podTemplateSpecPath: .spec.template
      statusDefinition:
        conditionsDefinition:
          messageFieldName: message
          path: .status.conditions
          statusFieldName: status
          typeFieldName: type
        statusMappings:
          running:
          - byConditions:
            - status: "True"
              type: Ready
