# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: krt
description: A Helm chart for deploying Karta (Krt) by NVIDIA.
type: application
version: 0.1.0
appVersion: "0.0.0"
