# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: krt
description: A Helm chart for deploying Karta (Krt) by NVIDIA.
type: application
version: 0.0.1
appVersion: "0.0.0"
annotations:
  org.opencontainers.image.source: https://github.com/run-ai/karta
  org.opencontainers.image.licenses: Apache-2.0
