# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: Chart lint
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ct-lint:
    name: Helm chart-testing (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up python (required by chart-testing)
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Set up helm
        uses: azure/setup-helm@v5

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.base_ref }} --chart-dirs charts
