# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 NVIDIA Corporation

name: Headlamp Plugin

on:
  push:
    branches: [ main, v0.* ]
    paths: [ 'headlamp-plugin/**', 'Makefile', '.github/workflows/headlamp-plugin-ci.yaml' ]
  pull_request:
    branches: [ main, v0.* ]
    paths: [ 'headlamp-plugin/**', 'Makefile', '.github/workflows/headlamp-plugin-ci.yaml' ]

permissions:
  contents: read

jobs:
  headlamp-plugin-ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Build Headlamp plugin
        run: make headlamp-plugin-build
